### ISSUE TITLE
Automated File Spanning

### ISSUE THREAD

**Issue by Sarci1** [ni/niveristand-embedded-data-logger-custom-device#2]
**Is your feature request related to a problem? Please describe.**
For long running tests, it would be ideal to be able to configure the CD to automatically span files based on a file size or a time. This would prevent the user from having to create a procedure or RT sequence for triggering it based on time. And it is cumbersome to trigger based on size today without having access to the file pointer directly.

**Describe the solution you'd like**
A configuration that forces the CD to generate a new file after a set file size or time has passed.

**Describe alternatives you've considered**
Another custom device to trigger the Log Command directly, but it doesn't have the granularity in file size one would prefer.

**Additional context**

**Comment by csjall** [comment]
I talked to Jarrod about this feature and he suggested that we look into using the Gateway Data Logging classes. These classes supersede the embedded data logger code and provide support for segmenting files and callbacks upon file completion. This code is currently used by the VeriStand Gateway and FlexLogger logging PE.

We should consider retrofitting the Embedded Data Logger engine to use these classes instead of natively calling into TDMS logging.
